CREATE TABLE `rp_dataengine.rp_device_profile_info`(
  `device` string,
  `inital_ts` string,
  `installed_app_tag` string,
  `finance_time` string,
  `finance_action` string,
  `installed_cate_tag` string,
  `portrait_cook_tag` string,
  `portrait_tour_tag` string,
  `imei` string,
  `cell_factory` int,
  `gender` int,
  `agebin` int,
  `segment` int,
  `edu` int,
  `kids` int,
  `income` int,
  `model_level` int,
  `tot_install_apps` int,
  `tags` string,
  `model` string,
  `carrier` string,
  `network` string,
  `screensize` string,
  `sysver` string,
  `city_level` int,
  `permanent_country` string,
  `permanent_province` string,
  `permanent_city` string,
  `occupation` int,
  `house` int,
  `repayment` int,
  `car` int,
  `workplace` string,
  `residence` string,
  `married` int,
  `update_time` string,
  `city` string,
  `country` string,
  `province` string)
COMMENT '设备全量标签'
PARTITIONED BY (
  `day` string COMMENT '全量数据,A|B分区切换'
) STORED AS orc;


CREATE TABLE rp_mobdi_app.rp_device_profile_full_view (
  device string COMMENT '设备ID',
  carrier string COMMENT '运营商',
  network string COMMENT '网络',
  cell_factory string COMMENT '设备品牌',
  sysver string COMMENT '操作系统版本',
  model string COMMENT '设备型号',
  model_level int COMMENT '设备档次',
  screensize string COMMENT '屏幕分辨率',
  country string COMMENT '国家(编码)',
  province string COMMENT '省份(编码)',
  city string COMMENT '城市(编码)',
  city_level int COMMENT '城市等级',
  country_cn string COMMENT '国家中文',
  province_cn string COMMENT '省份中文',
  city_cn string COMMENT '城市中文',
  breaked string COMMENT '是否越狱',
  city_level_1001 int COMMENT '新一线城市等级',
  public_date string COMMENT '发布日期',
  identity string COMMENT '特殊身份',
  gender int COMMENT '性别',
  agebin int COMMENT '年龄',
  car int COMMENT '汽车数',
  married int COMMENT '婚姻状态',
  edu int COMMENT '教育',
  income int COMMENT '收入',
  house int COMMENT '房产',
  kids int COMMENT '有无小孩',
  occupation int COMMENT '职业',
  industry int COMMENT '行业',
  life_stage string COMMENT '人生阶段',
  special_time string COMMENT '特殊时期',
  consum_level int COMMENT '消费水平',
  agebin_1001 int COMMENT '细分年龄',
  tag_list string COMMENT '标签列表',
  repayment int COMMENT '偿还能力',
  segment int COMMENT '人群',
  applist string COMMENT 'app安装列表',
  tot_install_apps int COMMENT 'app安装数量',
  nationality string COMMENT '国籍编码',
  nationality_cn string COMMENT '国籍中文',
  last_active string COMMENT '设备最后活跃时间',
  group_list string COMMENT '人群细分标签',
  first_active_time string COMMENT '设备首次出现时间',
  catelist string COMMENT '在装app的类别列表',
  permanent_country string COMMENT '常驻国家(编码)',
  permanent_province string COMMENT '常驻省份(编码)',
  permanent_city string COMMENT '常驻城市(编码)',
  permanent_country_cn string COMMENT '常驻国家(中文)',
  permanent_province_cn string COMMENT '常驻省份(中文)',
  permanent_city_cn string COMMENT '常驻城市(中文)',
  workplace string COMMENT '工作地',
  residence string COMMENT '常驻地',
  mapping_flag int COMMENT 'mapping标签flag',
  model_flag int COMMENT 'model socre标签flag',
  stats_flag int COMMENT '统计标签flag',
  processtime string COMMENT 'applist标签处理日期',
  processtime_all string COMMENT '整条数据最后的更新时间',
  price string COMMENT '设备价格',
  permanent_city_level int)
COMMENT '设备所有标签全量表'
STORED AS orc;