CREATE TABLE `dm_dataengine_mapping.dm_phone_mapping_v3`(
  `phone_md5` string COMMENT 'phone的md5值',
  `phone` string COMMENT 'phone',
  `device_plat` array<string> COMMENT 'android=1,ios=2',
  `device` array<string> COMMENT '设备id',
  `device_tm` array<string> COMMENT '设备id的更新时间',
  `duid` array<string> COMMENT 'duid',
  `update_time` string COMMENT '最新时间',
  `mac` array<string> COMMENT 'mac',
  `mac_md5` array<string>,
  `mac_tm` array<string> COMMENT 'mac的更新时间',
  `imei` array<string> COMMENT 'imei',
  `imei_md5` array<string>,
  `imei_tm` array<string> COMMENT 'imei的更新时间',
  `device_ltm` array<string> COMMENT '设备id的更新时间',
  `mac_ltm` array<string> COMMENT 'mac的更新时间',
  `imei_ltm` array<string> COMMENT 'imei的更新时间',
  `imei_14` array<string>,
  `imei_14_md5` array<string>,
  `imei_14_tm` array<string>,
  `imei_14_ltm` array<string>,
  `imei_15` array<string>,
  `imei_15_md5` array<string>,
  `imei_15_tm` array<string>,
  `imei_15_ltm` array<string>,
  `imsi` array<string>,
  `imsi_md5` array<string>,
  `imsi_tm` array<string>,
  `imsi_ltm` array<string>,
  `serialno` array<string>,
  `serialno_tm` array<string>,
  `serialno_ltm` array<string>,
  `idfa` array<string>,
  `idfa_tm` array<string>,
  `idfa_ltm` array<string>,
  `orig_imei` array<string> COMMENT 'orig_imei',
  `orig_imei_tm` array<string> COMMENT 'orig_imei_tm',
  `orig_imei_ltm` array<string> COMMENT 'orig_imei_ltm',
  `oaid` array<string> COMMENT 'oaid',
  `oaid_tm` array<string> COMMENT 'oaid_tm',
  `oaid_ltm` array<string> COMMENT 'oaid_ltm'
)
COMMENT 'phone=>device映射表'
PARTITIONED BY (
  `day` string COMMENT '创建时间')
stored as orc;

CREATE TABLE `dm_dataengine_mapping.dm_phone_mapping_v3_view`(
  `phone_md5` string COMMENT 'phone的md5值',
  `phone` string COMMENT 'phone',
  `device_plat` array<string> COMMENT 'android=1,ios=2',
  `device` array<string> COMMENT '设备id',
  `device_tm` array<string> COMMENT '设备id的更新时间',
  `duid` array<string> COMMENT 'duid',
  `update_time` string COMMENT '最新时间',
  `mac` array<string> COMMENT 'mac',
  `mac_md5` array<string>,
  `mac_tm` array<string> COMMENT 'mac的更新时间',
  `imei` array<string> COMMENT 'imei',
  `imei_md5` array<string>,
  `imei_tm` array<string> COMMENT 'imei的更新时间',
  `device_ltm` array<string> COMMENT '设备id的更新时间',
  `mac_ltm` array<string> COMMENT 'mac的更新时间',
  `imei_ltm` array<string> COMMENT 'imei的更新时间',
  `imei_14` array<string>,
  `imei_14_md5` array<string>,
  `imei_14_tm` array<string>,
  `imei_14_ltm` array<string>,
  `imei_15` array<string>,
  `imei_15_md5` array<string>,
  `imei_15_tm` array<string>,
  `imei_15_ltm` array<string>,
  `imsi` array<string>,
  `imsi_md5` array<string>,
  `imsi_tm` array<string>,
  `imsi_ltm` array<string>,
  `serialno` array<string>,
  `serialno_tm` array<string>,
  `serialno_ltm` array<string>,
  `idfa` array<string>,
  `idfa_tm` array<string>,
  `idfa_ltm` array<string>,
  `orig_imei` array<string> COMMENT 'orig_imei',
  `orig_imei_tm` array<string> COMMENT 'orig_imei_tm',
  `orig_imei_ltm` array<string> COMMENT 'orig_imei_ltm',
  `oaid` array<string> COMMENT 'oaid',
  `oaid_tm` array<string> COMMENT 'oaid_tm',
  `oaid_ltm` array<string> COMMENT 'oaid_ltm'
)
COMMENT 'phone=>device映射表'
PARTITIONED BY (
  `day` string COMMENT '创建时间')
stored as orc;