CREATE TABLE `rp_mobdi_app.mobfin_pid_profile_lable_full_par`(
                                                                 `pid` string COMMENT 'pid',
                                                                 `edu` int COMMENT '学历',
                                                                 `edu_cl` double COMMENT '学历预测值的置信度',
                                                                 `edu_source` int COMMENT '学历数据来源',
                                                                 `student` int COMMENT '职业(是否是学生)',
                                                                 `student_cl` double COMMENT '职业置信度',
                                                                 `student_source` int COMMENT '职业数据来源',
                                                                 `house` int COMMENT '是否有房',
                                                                 `house_cl` double COMMENT 'house预测值的置信度',
                                                                 `house_source` int COMMENT 'house数据来源',
                                                                 `car` int COMMENT '是否有车',
                                                                 `car_cl` double COMMENT 'car预测值的置信度',
                                                                 `car_source` int COMMENT 'car数据来源',
                                                                 `consume` int COMMENT '消费水平',
                                                                 `consume_cl` double COMMENT '消费水平置信度',
                                                                 `consume_source` int COMMENT '消费水平数据来源',
                                                                 `income` int COMMENT '收入',
                                                                 `income_cl` double COMMENT '收入预测值的置信度',
                                                                 `income_source` int COMMENT '收入数据来源',
                                                                 `married` int COMMENT '婚姻状态',
                                                                 `married_cl` double COMMENT '婚姻状态预测值的置信度',
                                                                 `married_source` int COMMENT '婚姻数据来源',
                                                                 `kids` int COMMENT '家庭中有无小孩，以及小孩年龄段',
                                                                 `kids_cl` double COMMENT 'kids预测值的置信度',
                                                                 `kids_source` int COMMENT 'kids数据来源',
                                                                 `provident_fund` int COMMENT '公积金',
                                                                 `provident_fund_cl` double COMMENT '公积金置信度',
                                                                 `provident_fund_source` int COMMENT '公积金数据来源',
                                                                 `social_security` int COMMENT '社保',
                                                                 `social_security_cl` double COMMENT '社保置信度',
                                                                 `social_security_source` int COMMENT '社保数据来源')
    COMMENT '金融线pid画像表'
    PARTITIONED BY (
        `day` string COMMENT '版本分区')